required_devices: 8
resume: false

no_test: false
test_only: false
debug: false
seed: 0
distributed: false
test_freq: 5
num_workers: 16

benchmark:
  name: "gym_set-full_finetune_UB_S1_112X112x32"

dataset:
  name: "gym_set_ub_s1"
  fold: 1
  batch_size: 32
  clip_duration: 2.0
  video_fps: 16.
  crop_size: 112
  transform: "msc+color"
  min_area: 0.08
  normalize: true
  switch_channels: false
  num_of_examples: 0
  color: [0.4, 0.4, 0.4, 0.2]
  train:
    split: "trainlist{fold:02d}"
    mode: "clip"
    clips_per_video: 10
    use_augmentation: true
    use_shuffle: true
    drop_last: true
  test:
    split: "testlist{fold:02d}"
    mode: "clip"
    clips_per_video: 3
    use_augmentation: false
    use_shuffle: false
    drop_last: false
  test_dense:
    split: "testlist{fold:02d}"
    mode: "video"
    clips_per_video: 10
    use_augmentation: false
    use_shuffle: false
    drop_last: false

optimizer:
  name: "adam"
  num_epochs: 18
  weight_decay: 0.0
  warmup_classifier: false
  lr:
    name: "multistep"
    base_lr: 0.0001
    gamma: 0.3
    milestones: [7, 12, 16]

model:
  args:
    n_classes: 15
    feat_dim: 512
